<?php include('server.php') ?>
<?php include('support_pages/searhLocations.php') ?>
<?php

print "<html>\n";
print "\n";
print "    <head>\n";
print "\n";
print "        <meta charset=\"UTF-8\">\n";
print "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
print "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0,maximum-scale=1\">\n";
print "\n";
print "\n";
print "\n";
print "        <!-- Loading third party fonts -->\n";
print "        <link href=\"http://fonts.googleapis.com/css?family=Roboto:300,400,700|\" rel=\"stylesheet\" type=\"text/css\">\n";
print "        <link href=\"fonts/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "\n";
print "        <!-- Loading main css file -->\n";
print "        <link rel=\"stylesheet\" href=\"style.css\">\n";
print "        <!-- Custom styles for this template -->\n";
print "        <link href=\"css/movies.css\" rel=\"stylesheet\">\n";
print "\n";
print "        <!--[if lt IE 9]>\n";
print "<script src=\"js/ie-support/html5.js\"></script>\n";
print "<script src=\"js/ie-support/respond.js\"></script>\n";
print "<![endif]-->\n";
print "\n";
print "        <title>Movie Locations Guide: Maps and Directions to Filming Locations</title>\n";
print "        <style>\n";
print "            /*\n";
print "            html,\n";
print "            body {\n";
print "            height: 100%;\n";
print "            margin: 0;\n";
print "            padding: 0;\n";
print "            }\n";
print "            */\n";
print "            #map,\n";
print "            #pano {\n";
print "                float: left;\n";
print "                height: 50%;\n";
print "                width: 50%;\n";
print "            }\n";
print "            .location{\n";
print "                height: auto;\n";
print "                width: auto;\n";
print "            }\n";
print "\n";
print "\n";
print "        </style>\n";
print "    </head>\n";
print "\n";
print "    <body>\n";
print "        <div id=\"site-content\">\n";
print "            <header class=\"site-header\">\n";
print "                <div class=\"container\">\n";
print "                    <a href=\"index.html\" id=\"branding\">\n";
print "                        <img src=\"images/logo.png\" alt=\"\" class=\"logo\">\n";
print "                        <div class=\"logo-copy\">\n";
print "                            <h1 class=\"site-title\">Scene This Before</h1>\n";
print "                            <small class=\"site-description\"> </small>\n";
print "                        </div>\n";
print "                    </a>\n";
print "                    <!-- #branding -->\n";
print "\n";
print "                    <div class=\"main-navigation\">\n";
print "                        <button type=\"button\" class=\"menu-toggle\"><i class=\"fa fa-bars\"></i></button>\n";
print "                        <ul class=\"menu\">\n";
print "                            <li class=\"menu-item\"><a href=\"index.php\">Home</a></li>\n";
print "                            <li class=\"menu-item\"><a href=\"movies.php\">Movies</a></li>\n";
print "                            <li class=\"menu-item\"><a href=\"series.php\">TV Series</a></li>\n";
print "                            <li class=\"menu-item current-menu-item\"><a href=\"getLocationInfo.php\">Locations</a></li>\n";
print "                            <li class=\"menu-item\"><a href=\"about.php\">About Us</a></li>\n";
print "                            <li class=\"menu-item\"><a href=\"signup.php\">Sign Up</a></li>\n";
print "                            <li class=\"menu-item\"><a href=\"login.php\">Log In</a></li>\n";
print "\n";
print "\n";
print "                        </ul>\n";
print "                        <!-- .menu -->\n";
print "\n";
print "                    </div>\n";
print "                    <!-- .main-navigation -->\n";
print "\n";
print "\n";
print "                    <div class=\"mobile-navigation\"></div>\n";
print "                </div>\n";
print "            </header>\n";
print "            <!--\n";
print "<header>\n";
print "<div class=\"container\">\n";
print "<h1><a href=\"/\">Scene This Before</a></h1>\n";
print "</div>\n";
print "<nav>\n";
print "<ul class=\"container\" id=\"navlist\">\n";
print "<li><a href=\"/movie-locations\">Movies</a></li>\n";
print "<li><a href=\"/tv-locations\">TV Shows</a></li>\n";
print "<li><a href=\"\">Locations</a></li>\n";
print "</ul>\n";
print "</nav>\n";
print "</header>\n";
print "-->\n";
print "            <div class=\"breadcrumb\">\n";
print "                <div class=\"container\">\n";
print "                    <h2>Friends</h2>\n";
print "                    <div class=\"share-button\"></div>\n";
print "                </div>\n";
print "            </div>\n";
print "            <div class=\"container\" >\n";
print "                <div class=\"inner\" >\n";
print "                    <main class=\"location\" >\n";
print "                        <h3>".$locationName."</h3>\n";
print "                        <p>\n";
print "                            ".$locationDescription."</p>\n";
print "                        <p></p>\n";

print "                        <div id=\"map\"></div>\n";
print "                        <div id=\"pano\"></div>\n";
print "            \n";
print "                        \n";
print "                        \n";
print "\n";
print "                        \n";
print "                    </main>\n";
print "                </div>\n";
print "            </div>\n";
print "            <footer class=\"site-footer\">\n";
print "            <div class=\"container\">\n";
print "                <div class=\"row\">\n";
print "                    <div class=\"col-md-2\">\n";
print "                        <div class=\"widget\">\n";
print "                            <h3 class=\"widget-title\">About Us</h3>\n";
print "                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia tempore vitae mollitia nesciunt saepe cupiditate</p>\n";
print "                        </div>\n";
print "                    </div>\n";
print "\n";
print "                </div>\n";
print "                <!-- .row -->\n";
print "\n";
print "                <div class=\"colophon\">Computer Science Assignment 2019</div>\n";
print "            </div>\n";
print "            <!-- .container -->\n";
print "\n";
print "        </footer>\n";
print "        </div>\n";
print "                        <script type=\"text/javascript\">\n";
print "                            var latitude=".$latitude.";\n";
print "                            var longtitude=".$longtitude."\n";
print "                            function initialize() {\n";
print "                                var fenway = {\n";
print "                                    lat: latitude,\n";
print "                                    lng: longtitude\n";
print "                                }; //40°43'56.493\" N -74°0'19.08\" E\n";
print "                                var map = new google.maps.Map(document.getElementById('map'), {\n";
print "                                    center: fenway,\n";
print "                                    zoom: 14\n";
print "                                });\n";
print "                                var panorama = new google.maps.StreetViewPanorama(document.getElementById('pano'), {\n";
print "                                    position: fenway,\n";
print "                                    pov: {\n";
print "                                        heading:".$heading.",\n";
print "                                        pitch: 10\n";
print "                                    }\n";
print "                                });\n";
print "                                map.setStreetView(panorama);\n";
print "                            }\n";
print "\n";
print "                        </script>\n";
print "                        <script async defer\n";
print "                                src=\"//maps.googleapis.com/maps/api/js?key=AIzaSyB2Kyy8TS2MGcHCYv68hK4-NPfASWe6LV0&callback=initialize\" type=\"text/javascript\">\n";
print "                        </script>\n";
print "    </body>\n";
print "</html>\n";

?>
